### ISSUE TITLE
Cannot build Debian package

### ISSUE THREAD

**Issue by ghost** [jonalmeida/UberWriter#1]
$ sudo ./debian/rules 
dh_auto_install -- --install-scripts=/opt/extras.ubuntu.com/uberwriter/bin  --install-data=/opt/extras.ubuntu.com/uberwriter --install-lib=/opt/extras.ubuntu.com/uberwriter
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    'pylocales' : ['locales.db']
  File "/usr/lib/python2.7/dist-packages/DistUtilsExtra/auto.py", line 98, in setup
    **requires(attrs, src_all)
  File "/usr/lib/python2.7/dist-packages/DistUtilsExtra/auto.py", line 470, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python2.7/dist-packages/DistUtilsExtra/auto.py", line 404, in __add_imports
    if alias.name and __external_mod(cur_module, alias.name, attrs):
  File "/usr/lib/python2.7/dist-packages/DistUtilsExtra/auto.py", line 353, in __external_mod
    mod = __import**(cur_module + '.' + module)
  File "/home/data1/protected/Programming/git/UberWriter/uberwriter_lib/**init**.py", line 22, in <module>
    from . helpers import set_up_logging
  File "/home/data1/protected/Programming/git/UberWriter/uberwriter_lib/helpers.py", line 24, in <module>
    from . Builder import Builder
  File "/home/data1/protected/Programming/git/UberWriter/uberwriter_lib/Builder.py", line 21, in <module>
    from gi.repository import GObject, Gtk # pylint: disable=E0611
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 291, in _load
    overrides_modules = __import__('gi.overrides', fromlist=[self._namespace])
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 59, in <module>
    globals()[name] = gi.overrides.deprecated(getattr(GLib, name), 'GLib.' + name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 316, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 135, in __getattr__
    self.**name**, name))
AttributeError: 'gi.repository.GLib' object has no attribute 'uri_list_extract_uris'
dh_auto_install: python setup.py install --force --root=/home/data1/protected/Programming/git/UberWriter/debian/uberwriter --no-compile -O0 --install-scripts=/opt/extras.ubuntu.com/uberwriter/bin --install-data=/opt/extras.ubuntu.com/uberwriter --install-lib=/opt/extras.ubuntu.com/uberwriter --install-layout=deb returned exit code 1
make: **\* [override_dh_auto_install] Error 1

**Comment by jonalmeida** [comment]
So apparently I don't get emails for new issues even though it's my own repo..

I'll have a look at this sometime this week and post and update.

**Comment by jonalmeida** [comment]
Update: Other events in my agenda kept coming up so I haven't been able to get on this yet since this involves a decent bit of research and time on my side.

This is still on my list.
